spring:
  sql:
    init:
      mode: ALWAYS
  datasource:
    url: jdbc:h2:file:./db/filmorate
    username: sa
    password: password
    driverClassName: org.h2.Driver
logging:
  level:
    org:
      zalando:
        logbook: TRACE