
CREATE TABLE "Mpa" (
  "Mpa_id" integer PRIMARY KEY,
  "Mpa_name" varchar(5) NOT NULL UNIQUE CHECK("Mpa_name" IN ('G', 'PG', 'PG-13', 'R', 'NC-17'))
);

CREATE TABLE "Films" (
  "Film_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Film_name" varchar(55) NOT NULL,
  "Film_description" varchar(512),
  "Film_release_date" date,
  "Film_duration" integer,
  "Mpa_id" integer,
  FOREIGN KEY ("Mpa_id") REFERENCES "Mpa" ("Mpa_id") ON DELETE SET NULL
);

CREATE TABLE "Genres" (
  "Genre_id" integer PRIMARY KEY,
  "Genre_name" varchar(35) NOT NULL UNIQUE
);

CREATE TABLE "Genre_film" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Genre_id" integer NOT NULL,
  "Film_id" integer NOT NULL,
  FOREIGN KEY ("Film_id") REFERENCES "Films" ("Film_id") ON DELETE CASCADE,
  FOREIGN KEY ("Genre_id") REFERENCES "Genres" ("Genre_id") ON DELETE CASCADE,
  UNIQUE ("Genre_id", "Film_id")
);

CREATE TABLE "Users" (
  "User_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Login" varchar(60) NOT NULL UNIQUE,
  "Username" varchar(55),
  "Email" varchar(127) NOT NULL UNIQUE,
  "Birthday" date
);

CREATE TABLE "Friends" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "User_id" integer NOT NULL,
  "Friend_id" integer NOT NULL,
  FOREIGN KEY ("User_id") REFERENCES "Users" ("User_id") ON DELETE CASCADE,
  FOREIGN KEY ("Friend_id") REFERENCES "Users" ("User_id") ON DELETE CASCADE,
  UNIQUE("User_id", "Friend_id")
);

CREATE TABLE "Likes" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Film_id" integer NOT NULL,
  "User_id" integer NOT NULL,
  FOREIGN KEY ("User_id") REFERENCES "Users" ("User_id") ON DELETE CASCADE,
  FOREIGN KEY ("Film_id") REFERENCES "Films" ("Film_id") ON DELETE CASCADE,
  UNIQUE ("Film_id", "User_id")
);
